---
- name: Example of Ansible Playbook
  hosts: all

  tasks:
  - name: copy file hosts with permissions
    ansible.builtin.copy:
      src: ./hosts
      dest: /tmp/hosts_backup
      mode: "0644"
  - name: Add the user 'tess'
    ansible.builtin.user:
      name: tess
    become: yes
    become_method: sudo

  - name: upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes

