---
- name: Deploy LAMP on Ubuntu hosts
  hosts: ubuntu
  become: yes
  become_method: sudo
  
  vars_files:
  - vars/linuxsecrets.yml

  pre_tasks:
  - name: Update apt repository cache, if necessary
    apt: update_cache=yes cache_valid_time=3600

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

  tasks:
  - name: Install LAMP packages
    apt:
      state: present
      name:
      - apache2
      - mariadb-server
      - mariadb-client
      - php

  - name: this is a testing task to print the user variable name
    debug:
      msg: "variable value is {{ user }}"

  - name: add user "{{ user }}"
    user: 
      name: "{{ user }}"
      group: sys

  - name: set permissions on home directory for "{{ user }}"
    file: 
      path: "/home/{{ user }} "
      state: directory
      mode: '0755'

  - name: create the public_html subdirectory "{{ user }}"
    file:
      path: "/home/{{ user }}/public_html"
      state: directory
      mode: '0755'

  - name: upload sample index.html file
    copy:
      src: ./index.html
      dest: "/home/{{ user }}/public_html/index.html"
      owner: root
      group: sys
      mode: '0644'
    
  - name: Disable the firewall
    service: name=ufw state=stopped

  - name: Start Apache and MariaDB
    service: "name={{ item }} state=started enabled=yes"
    with_items:
    - apache2
    - mariadb

  - name: Enable Apache userdir module for home directory hosting
    apache2_module: name=userdir state=present
    notify: restart apache
