---
- name: install and start apache
  hosts: fedora
  become: yes
  become_method: sudo
  
  tasks:
    - name: ensure apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: ensure apache is started
      service:
        name: apache2
        state: started

